[pytest]
addopts = --alluredir=./allure-results --clean-alluredir -v -s
markers =
    smoke: Critical tests to verify the applications basic stability.
    regression: Tests to ensure that new code changes have not broken existing features.
    functional: Tests verifying the core business functions of the application.
    security: Tests focusing on authentication, authorization, and security.
    negative: Tests that verify how the system handles invalid input or failure scenarios.
    performance: Tests for system latency, load, and responsiveness.
    api_integration: Tests validating interaction between UI and API.
    ui_only: Tests focused strictly on visual elements and UI behavior.
    complex_logic: Tests for intricate business rules or multi-step workflows.
    data_driven: Tests that utilize external data sources (CSV, JSON, etc.).
    sanity: Brief, focused tests to verify specific components or fixed bugs.
    logic: marks tests that verify business logic (calculate prices, etc.)