name: CI Environment Test

on:
  push:
    branches: [ main ] # וודא שזה השם של ה-Branch הראשי שלך

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "The GitHub Action is working correctly!"