name: Hotel Booking Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # כאן אנחנו מגדירים את הריצות המקבילות
        browser_name: ['CHROME', 'FIREFOX']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      # --- עדכון הנתיב לתיקיית config ---
      - name: Update Config for ${{ matrix.browser_name }}
        run: |
          sed -i 's/"BROWSER_TYPE":"CHROME"/"BROWSER_TYPE":"${{ matrix.browser_name }}"/g' config/config.json
          echo "Updated Config Content:"
          cat config/config.json

      - name: Run Pytest
        run: xvfb-run pytest tests/ -v